### PR TITLE
Added support for python3

### PR DESCRIPTION
**Pull request by dwighthubbard**
Switched to using argparse to get command line arguments.

Fix some formatting issues to comply with the PEP8 python
style guide.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by diracdeltas** [comment]
Thanks, Dwight. This should apply cleanly to https://github.com/google/end-to-end (the upstream of this repo). Would you mind signing the Google CLA and opening it there?

I think it's best to keep the build files and crypto library parts of Google/Yahoo End to End as similar as possible for now.

**Comment by coruus** [comment]
I'm happy to merge this pro tem, pending some more substantial changes to build system. (Which is unacceptably slow right now.) So: LGTM and merged.

**Comment by diracdeltas** [comment]
This breaks the testserver for me. Is it just my python environment, or does `do.sh testserver` fail for others too?

**Pull request merged**
